apiVersion: v1
kind: Service
metadata:
  name: ddc-example-rds-python
  labels:
    app: ddc-example-rds-python
spec:
  type: NodePort
  ports:
  - name: ddc-example-rds-python
    protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: ddc-example-rds-python
